import express from "express";
import Database from "better-sqlite3";
import crypto from "node:crypto";
import path from "node:path";
import {fileURLToPath} from "node:url";
const dir=path.dirname(fileURLToPath(import.meta.url)),app=express(),db=new Database(path.join(dir,"screenvault.db"));
db.pragma("foreign_keys=ON");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password_hash TEXT,role TEXT,display_name TEXT,verified INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id INTEGER,csrf TEXT,expires INTEGER);
CREATE TABLE IF NOT EXISTS productions(id INTEGER PRIMARY KEY,name TEXT,owner_id INTEGER,classification TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS auditions(id INTEGER PRIMARY KEY,production_id INTEGER,actor_id INTEGER,title TEXT,status TEXT,media_key TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS likeness(id INTEGER PRIMARY KEY,user_id INTEGER,production_id INTEGER,feature_film INTEGER,tv INTEGER,promotion INTEGER,ai_training INTEGER,synthetic_performance INTEGER,synthetic_voice INTEGER,posthumous_replication INTEGER,UNIQUE(user_id,production_id));
CREATE TABLE IF NOT EXISTS provenance(id INTEGER PRIMARY KEY,audition_id INTEGER,sha256 TEXT,watermark TEXT,ai_risk TEXT);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id INTEGER,action TEXT,target TEXT,ip TEXT,created_at TEXT);`);
const hash=p=>{const s=crypto.randomBytes(16).toString("hex");return s+":"+crypto.scryptSync(p,s,64).toString("hex")};
const check=(p,h)=>{const [s,e]=h.split(":");const a=crypto.scryptSync(p,s,64),b=Buffer.from(e,"hex");return a.length===b.length&&crypto.timingSafeEqual(a,b)};
const seed=(e,p,r,n)=>{if(!db.prepare("SELECT id FROM users WHERE email=?").get(e))db.prepare("INSERT INTO users(email,password_hash,role,display_name,verified)VALUES(?,?,?,?,1)").run(e,hash(p),r,n)};
seed("actor@screenvault.local","ActorDemo123!","ACTOR","Demo Actor");
seed("casting@screenvault.local","CastingDemo123!","CASTING","Demo Casting Director");
function ck(h=""){return Object.fromEntries(h.split(";").map(x=>x.trim()).filter(Boolean).map(x=>{let i=x.indexOf("=");return[x.slice(0,i),x.slice(i+1)]}))}
function audit(uid,a,t,ip){db.prepare("INSERT INTO audit(user_id,action,target,ip,created_at)VALUES(?,?,?,?,?)").run(uid,a,t,ip,new Date().toISOString())}
function auth(req,res,next){let sid=ck(req.headers.cookie).sv_session,s=db.prepare("SELECT s.*,u.email,u.role,u.display_name,u.verified FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires> ?").get(sid,Date.now());if(!s)return res.status(401).json({error:"Authentication required"});req.user={id:s.user_id,email:s.email,role:s.role,name:s.display_name,verified:!!s.verified};req.session=s;next()}
function csrf(req,res,next){if(["POST","PUT","DELETE","PATCH"].includes(req.method)&&req.headers["x-csrf-token"]!==req.session.csrf)return res.status(403).json({error:"CSRF validation failed"});next()}
function role(...r){return(req,res,next)=>r.includes(req.user.role)?next():res.status(403).json({error:"Insufficient permissions"})}
app.disable("x-powered-by");app.use(express.json({limit:"100kb"}));app.use((req,res,next)=>{res.setHeader("Content-Security-Policy","default-src 'self';style-src 'self' 'unsafe-inline';script-src 'self';frame-ancestors 'none';base-uri 'self'");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","no-referrer");next()});
app.post("/api/login",(req,res)=>{let e=String(req.body.email||"").toLowerCase(),u=db.prepare("SELECT * FROM users WHERE email=?").get(e);if(!u||!check(String(req.body.password||""),u.password_hash)){audit(null,"LOGIN_FAILED",e,req.ip);return res.status(401).json({error:"Invalid credentials"})}let id=crypto.randomBytes(32).toString("hex"),c=crypto.randomBytes(24).toString("hex");db.prepare("INSERT INTO sessions VALUES(?,?,?,?)").run(id,u.id,c,Date.now()+14400000);audit(u.id,"LOGIN_SUCCESS","session",req.ip);res.setHeader("Set-Cookie",`sv_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=14400`);res.json({user:{id:u.id,email:u.email,role:u.role,name:u.display_name,verified:!!u.verified},csrf:c})});
app.get("/api/me",auth,(req,res)=>res.json({user:req.user,csrf:req.session.csrf}));
app.post("/api/logout",auth,csrf,(req,res)=>{db.prepare("DELETE FROM sessions WHERE id=?").run(req.session.id);res.setHeader("Set-Cookie","sv_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0");res.json({ok:true})});
app.get("/api/actors",auth,role("CASTING","ADMIN"),(req,res)=>res.json(db.prepare("SELECT id,email,display_name,verified FROM users WHERE role='ACTOR'").all()));
app.get("/api/productions",auth,(req,res)=>res.json(db.prepare("SELECT p.*,u.email owner FROM productions p JOIN users u ON u.id=p.owner_id WHERE ?='ADMIN' OR p.owner_id=? OR EXISTS(SELECT 1 FROM auditions a WHERE a.production_id=p.id AND a.actor_id=?) ORDER BY p.id DESC").all(req.user.role,req.user.id,req.user.id)));
app.post("/api/productions",auth,csrf,role("CASTING","ADMIN"),(req,res)=>{let n=String(req.body.name||"").trim();if(!n)return res.status(400).json({error:"Name required"});let r=db.prepare("INSERT INTO productions(name,owner_id,classification,created_at)VALUES(?,?,?,?)").run(n,req.user.id,req.body.classification||"CONFIDENTIAL",new Date().toISOString());audit(req.user.id,"CREATE_PRODUCTION","production:"+r.lastInsertRowid,req.ip);res.json({id:r.lastInsertRowid})});
app.get("/api/auditions",auth,(req,res)=>res.json(db.prepare("SELECT a.*,p.name production,u.email actor FROM auditions a JOIN productions p ON p.id=a.production_id JOIN users u ON u.id=a.actor_id WHERE a.actor_id=? OR p.owner_id=? OR ?='ADMIN' ORDER BY a.id DESC").all(req.user.id,req.user.id,req.user.role)));
app.post("/api/auditions",auth,csrf,role("CASTING","ADMIN"),(req,res)=>{let p=db.prepare("SELECT * FROM productions WHERE id=?").get(+req.body.productionId),a=db.prepare("SELECT * FROM users WHERE id=? AND role='ACTOR'").get(+req.body.actorId);if(!p||!a||(req.user.role!=="ADMIN"&&p.owner_id!==req.user.id))return res.status(403).json({error:"Invalid production/actor access"});let r=db.prepare("INSERT INTO auditions(production_id,actor_id,title,status,media_key,created_at)VALUES(?,?,?,?,?,?)").run(p.id,a.id,String(req.body.title||"Audition"),"INVITED",crypto.randomUUID(),new Date().toISOString());audit(req.user.id,"CREATE_AUDITION","audition:"+r.lastInsertRowid,req.ip);res.json({id:r.lastInsertRowid})});
app.get("/api/auditions/:id/media-url",auth,(req,res)=>{let a=db.prepare("SELECT a.*,p.owner_id FROM auditions a JOIN productions p ON p.id=a.production_id WHERE a.id=?").get(+req.params.id);if(!a)return res.status(404).json({error:"Not found"});if(req.user.role!=="ADMIN"&&req.user.id!==a.actor_id&&req.user.id!==a.owner_id){audit(req.user.id,"MEDIA_ACCESS_DENIED","audition:"+a.id,req.ip);return res.status(403).json({error:"Media access denied"})}let exp=Date.now()+60000,p=a.id+":"+exp+":"+a.media_key,s=crypto.createHmac("sha256",process.env.MEDIA_SIGNING_SECRET||"DEV_ONLY_CHANGE_ME").update(p).digest("hex");audit(req.user.id,"MEDIA_URL_ISSUED","audition:"+a.id,req.ip);res.json({url:`/demo-media/${a.id}?exp=${exp}&sig=${s}`,expires:exp})});
app.get("/demo-media/:id",(req,res)=>{let a=db.prepare("SELECT * FROM auditions WHERE id=?").get(+req.params.id),exp=+req.query.exp,sig=String(req.query.sig||"");if(!a)return res.status(404).send("Not found");let p=a.id+":"+exp+":"+a.media_key,s=crypto.createHmac("sha256",process.env.MEDIA_SIGNING_SECRET||"DEV_ONLY_CHANGE_ME").update(p).digest("hex");if(!exp||Date.now()>exp||sig.length!==s.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(s)))return res.status(403).send("Expired or invalid");res.type("text/plain").send("DEMO MEDIA OBJECT — replace with private cloud object storage in production.")});
app.put("/api/likeness/:pid",auth,csrf,role("ACTOR","ADMIN"),(req,res)=>{let p=db.prepare("SELECT id FROM productions WHERE id=?").get(+req.params.pid);if(!p)return res.status(404).json({error:"Production not found"});let k=["feature_film","tv","promotion","ai_training","synthetic_performance","synthetic_voice","posthumous_replication"],v=k.map(x=>req.body[x]?1:0);db.prepare(`INSERT INTO likeness(user_id,production_id,${k.join(",")})VALUES(?, ?, ${k.map(()=>"?").join(",")}) ON CONFLICT(user_id,production_id) DO UPDATE SET ${k.map(x=>x+"=excluded."+x).join(",")}`).run(req.user.id,p.id,...v);audit(req.user.id,"UPDATE_LIKENESS_POLICY","production:"+p.id,req.ip);res.json({ok:true})});
app.get("/api/likeness/:pid",auth,(req,res)=>res.json(db.prepare("SELECT * FROM likeness WHERE user_id=? AND production_id=?").get(req.user.id,+req.params.pid)||{}));
app.get("/api/provenance/:id",auth,(req,res)=>{let a=db.prepare("SELECT * FROM auditions WHERE id=?").get(+req.params.id);if(!a)return res.status(404).json({error:"Not found"});let r=db.prepare("SELECT * FROM provenance WHERE audition_id=?").get(a.id);if(!r){let h=crypto.createHash("sha256").update(a.media_key).digest("hex"),w="SV-"+crypto.randomBytes(6).toString("hex").toUpperCase();db.prepare("INSERT INTO provenance(audition_id,sha256,watermark,ai_risk)VALUES(?,?,?,?)").run(a.id,h,w,"UNASSESSED");r=db.prepare("SELECT * FROM provenance WHERE audition_id=?").get(a.id)}res.json(r)});
app.get("/api/audit",auth,role("CASTING","ADMIN"),(req,res)=>res.json(db.prepare("SELECT l.*,u.email FROM audit l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.id DESC LIMIT 200").all()));
app.use(express.static(path.join(dir,"public")));app.get("*",(req,res)=>res.sendFile(path.join(dir,"public/index.html")));
if(process.env.NODE_ENV!=="test")app.listen(process.env.PORT||3000,()=>console.log("ScreenVault V1.0 on http://localhost:3000"));
export {app,db};